/**
 * Base de datos enriquecida de Fruityvice con traducciones en español,
 * emojis representativos, colores temáticos y propiedades saludables.
 */
export const FRUITS_DATABASE = [
  {
    name: "Apple",
    spanishName: "Manzana",
    id: 6,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Malus",
    emoji: "🍎",
    accentColor: "#ef4444",
    bgGradient: "linear-gradient(135deg, rgba(239, 68, 68, 0.15), rgba(220, 38, 38, 0.05))",
    benefits: ["Rica en fibra soluble (pectina)", "Regula los niveles de glucosa", "Buena para la salud dental"],
    nutritions: { calories: 52, fat: 0.2, sugar: 10.3, carbohydrates: 11.4, protein: 0.3 }
  },
  {
    name: "Apricot",
    spanishName: "Albaricoque / Damasco",
    id: 35,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    emoji: "🍑",
    accentColor: "#f97316",
    bgGradient: "linear-gradient(135deg, rgba(249, 115, 22, 0.15), rgba(234, 88, 12, 0.05))",
    benefits: ["Rico en vitamina A y betacarotenos", "Protege la salud ocular", "Favorece la digestión"],
    nutritions: { calories: 48, fat: 0.4, sugar: 9.2, carbohydrates: 11.1, protein: 1.4 }
  },
  {
    name: "Avocado",
    spanishName: "Aguacate / Palta",
    id: 84,
    family: "Lauraceae",
    order: "Laurales",
    genus: "Persea",
    emoji: "🥑",
    accentColor: "#84cc16",
    bgGradient: "linear-gradient(135deg, rgba(132, 204, 22, 0.15), rgba(101, 163, 13, 0.05))",
    benefits: ["Grasas monoinsaturadas saludables", "Excelente fuente de potasio", "Protege el corazón"],
    nutritions: { calories: 160, fat: 14.7, sugar: 0.7, carbohydrates: 8.5, protein: 2.0 }
  },
  {
    name: "Banana",
    spanishName: "Plátano / Banano",
    id: 1,
    family: "Musaceae",
    order: "Zingiberales",
    genus: "Musa",
    emoji: "🍌",
    accentColor: "#eab308",
    bgGradient: "linear-gradient(135deg, rgba(234, 179, 8, 0.15), rgba(202, 138, 4, 0.05))",
    benefits: ["Energía rápida para deportistas", "Alto contenido de potasio y B6", "Reduce calambres musculares"],
    nutritions: { calories: 96, fat: 0.2, sugar: 17.2, carbohydrates: 22.0, protein: 1.0 }
  },
  {
    name: "Blackberry",
    spanishName: "Mora / Zarzamora",
    id: 64,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Rubus",
    emoji: "🫐",
    accentColor: "#6b21a8",
    bgGradient: "linear-gradient(135deg, rgba(107, 33, 168, 0.15), rgba(88, 28, 135, 0.05))",
    benefits: ["Poderoso antioxidante (antocianinas)", "Baja en calorías", "Favorece la salud cerebral"],
    nutritions: { calories: 40, fat: 0.4, sugar: 4.5, carbohydrates: 9.0, protein: 1.3 }
  },
  {
    name: "Blueberry",
    spanishName: "Arándano azul",
    id: 33,
    family: "Ericaceae",
    order: "Ericales",
    genus: "Vaccinium",
    emoji: "🫐",
    accentColor: "#3b82f6",
    bgGradient: "linear-gradient(135deg, rgba(59, 130, 246, 0.15), rgba(37, 99, 235, 0.05))",
    benefits: ["Rey de los antioxidantes", "Mejora la memoria y función cerebral", "Cuida el sistema urinario"],
    nutritions: { calories: 29, fat: 0.3, sugar: 5.4, carbohydrates: 5.5, protein: 0.7 }
  },
  {
    name: "Cherry",
    spanishName: "Cereza",
    id: 9,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    emoji: "🍒",
    accentColor: "#dc2626",
    bgGradient: "linear-gradient(135deg, rgba(220, 38, 38, 0.15), rgba(185, 28, 28, 0.05))",
    benefits: ["Contiene melatonina natural (mejora el sueño)", "Propiedades antiinflamatorias", "Alivia dolores articulares"],
    nutritions: { calories: 50, fat: 0.3, sugar: 8.0, carbohydrates: 12.0, protein: 1.0 }
  },
  {
    name: "Cranberry",
    spanishName: "Arándano rojo",
    id: 107,
    family: "Ericaceae",
    order: "Ericales",
    genus: "Vaccinium",
    emoji: "🍒",
    accentColor: "#991b1b",
    bgGradient: "linear-gradient(135deg, rgba(153, 27, 27, 0.15), rgba(127, 29, 29, 0.05))",
    benefits: ["Previene infecciones de vías urinarias", "Salud cardiovascular", "Alto en vitamina C"],
    nutritions: { calories: 46, fat: 0.1, sugar: 4.0, carbohydrates: 12.2, protein: 0.4 }
  },
  {
    name: "Dragonfruit",
    spanishName: "Pitahaya / Fruta del Dragón",
    id: 80,
    family: "Cactaceae",
    order: "Caryophyllales",
    genus: "Selenicereus",
    emoji: "🐉",
    accentColor: "#ec4899",
    bgGradient: "linear-gradient(135deg, rgba(236, 72, 153, 0.15), rgba(219, 39, 119, 0.05))",
    benefits: ["Exótica y rica en prebióticos", "Estimula el colágeno", "Fortalece la flora intestinal"],
    nutritions: { calories: 60, fat: 1.5, sugar: 8.0, carbohydrates: 9.0, protein: 9.0 }
  },
  {
    name: "Durian",
    spanishName: "Durián",
    id: 85,
    family: "Malvaceae",
    order: "Malvales",
    genus: "Durio",
    emoji: "🍈",
    accentColor: "#a3e635",
    bgGradient: "linear-gradient(135deg, rgba(163, 230, 53, 0.15), rgba(132, 204, 22, 0.05))",
    benefits: ["Densidad energética excepcional", "Rico en vitaminas del complejo B", "Minerales esenciales"],
    nutritions: { calories: 147, fat: 5.3, sugar: 6.75, carbohydrates: 27.1, protein: 1.5 }
  },
  {
    name: "Feijoa",
    spanishName: "Feijoa / Guayabo del Brasil",
    id: 76,
    family: "Myrtaceae",
    order: "Myrtales",
    genus: "Acca",
    emoji: "🍈",
    accentColor: "#15803d",
    bgGradient: "linear-gradient(135deg, rgba(21, 128, 61, 0.15), rgba(22, 101, 52, 0.05))",
    benefits: ["Aporte elevado de yodo y fibra", "Refuerza defensas inmunológicas", "Refrescante y digestiva"],
    nutritions: { calories: 61, fat: 0.6, sugar: 8.0, carbohydrates: 15.0, protein: 1.2 }
  },
  {
    name: "Fig",
    spanishName: "Higo",
    id: 68,
    family: "Moraceae",
    order: "Rosales",
    genus: "Ficus",
    emoji: "🫒",
    accentColor: "#7e22ce",
    bgGradient: "linear-gradient(135deg, rgba(126, 34, 206, 0.15), rgba(107, 33, 168, 0.05))",
    benefits: ["Rico en calcio vegetal", "Digestión óptima y alivio de estreñimiento", "Sabor dulce natural"],
    nutritions: { calories: 74, fat: 0.3, sugar: 16.0, carbohydrates: 19.0, protein: 0.8 }
  },
  {
    name: "Gooseberry",
    spanishName: "Grosella / Uchuva silvestre",
    id: 69,
    family: "Grossulariaceae",
    order: "Saxifragales",
    genus: "Ribes",
    emoji: "🟢",
    accentColor: "#65a30d",
    bgGradient: "linear-gradient(135deg, rgba(101, 163, 13, 0.15), rgba(77, 124, 15, 0.05))",
    benefits: ["Vitamina C concentrada", "Cuidado de la piel y cabello", "Control de lípidos en sangre"],
    nutritions: { calories: 44, fat: 0.6, sugar: 0.0, carbohydrates: 10.0, protein: 0.9 }
  },
  {
    name: "Grape",
    spanishName: "Uva",
    id: 81,
    family: "Vitaceae",
    order: "Vitales",
    genus: "Vitis",
    emoji: "🍇",
    accentColor: "#8b5cf6",
    bgGradient: "linear-gradient(135deg, rgba(139, 92, 246, 0.15), rgba(124, 58, 237, 0.05))",
    benefits: ["Contiene resveratrol cardioprotector", "Mejora la circulación", "Poder hidratante"],
    nutritions: { calories: 69, fat: 0.16, sugar: 16.0, carbohydrates: 18.1, protein: 0.72 }
  },
  {
    name: "GreenApple",
    spanishName: "Manzana Verde (Granny Smith)",
    id: 72,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Malus",
    emoji: "🍏",
    accentColor: "#22c55e",
    bgGradient: "linear-gradient(135deg, rgba(34, 197, 94, 0.15), rgba(22, 163, 74, 0.05))",
    benefits: ["Menos azúcar que la manzana roja", "Ácido málico digestivo", "Excelente saciedad"],
    nutritions: { calories: 21, fat: 0.1, sugar: 9.6, carbohydrates: 3.1, protein: 0.4 }
  },
  {
    name: "Guava",
    spanishName: "Guayaba",
    id: 37,
    family: "Myrtaceae",
    order: "Myrtales",
    genus: "Psidium",
    emoji: "🍈",
    accentColor: "#10b981",
    bgGradient: "linear-gradient(135deg, rgba(16, 185, 129, 0.15), rgba(5, 150, 105, 0.05))",
    benefits: ["4 veces más vitamina C que la naranja", "Superalimento inmunológico", "Alta en fibra dietética"],
    nutritions: { calories: 68, fat: 1.0, sugar: 9.0, carbohydrates: 14.0, protein: 2.6 }
  },
  {
    name: "Kiwi",
    spanishName: "Kiwi",
    id: 66,
    family: "Actinidiaceae",
    order: "Ericales",
    genus: "Actinidia",
    emoji: "🥝",
    accentColor: "#84cc16",
    bgGradient: "linear-gradient(135deg, rgba(132, 204, 22, 0.15), rgba(101, 163, 13, 0.05))",
    benefits: ["Enzima actinidina (facilita digestión de proteínas)", "Vitamina C extrema", "Favorece el descanso"],
    nutritions: { calories: 61, fat: 0.5, sugar: 9.0, carbohydrates: 15.0, protein: 1.1 }
  },
  {
    name: "Lemon",
    spanishName: "Limón",
    id: 26,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    emoji: "🍋",
    accentColor: "#facc15",
    bgGradient: "linear-gradient(135deg, rgba(250, 204, 21, 0.15), rgba(234, 179, 8, 0.05))",
    benefits: ["Poder alcalinizante y digestivo", "Muy bajo en calorías y azúcares", "Estimula la absorción de hierro"],
    nutritions: { calories: 29, fat: 0.3, sugar: 2.5, carbohydrates: 9.0, protein: 1.1 }
  },
  {
    name: "Lime",
    spanishName: "Lima",
    id: 44,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    emoji: "🍋‍🟩",
    accentColor: "#84cc16",
    bgGradient: "linear-gradient(135deg, rgba(132, 204, 22, 0.15), rgba(101, 163, 13, 0.05))",
    benefits: ["Refrescante e hidratante", "Ácido cítrico antibacterial", "Perfecta para aderezos saludables"],
    nutritions: { calories: 25, fat: 0.1, sugar: 1.7, carbohydrates: 8.4, protein: 0.3 }
  },
  {
    name: "Lingonberry",
    spanishName: "Arándano rojo del norte",
    id: 65,
    family: "Ericaceae",
    order: "Ericales",
    genus: "Vaccinium",
    emoji: "🍒",
    accentColor: "#b91c1c",
    bgGradient: "linear-gradient(135deg, rgba(185, 28, 28, 0.15), rgba(153, 27, 27, 0.05))",
    benefits: ["Propiedades antiinflamatorias", "Estudios para el control de peso", "Rico en flavonoides"],
    nutritions: { calories: 50, fat: 0.3, sugar: 5.7, carbohydrates: 11.3, protein: 0.7 }
  },
  {
    name: "Lychee",
    spanishName: "Lichi",
    id: 67,
    family: "Sapindaceae",
    order: "Sapindales",
    genus: "Litchi",
    emoji: "⚪",
    accentColor: "#f43f5e",
    bgGradient: "linear-gradient(135deg, rgba(244, 63, 94, 0.15), rgba(225, 29, 72, 0.05))",
    benefits: ["Sabor floral y dulce exquisito", "Rico en oligonol (antioxidante)", "Hidratación celular"],
    nutritions: { calories: 66, fat: 0.44, sugar: 15.0, carbohydrates: 17.0, protein: 0.8 }
  },
  {
    name: "Mango",
    spanishName: "Mango",
    id: 27,
    family: "Anacardiaceae",
    order: "Sapindales",
    genus: "Mangifera",
    emoji: "🥭",
    accentColor: "#f59e0b",
    bgGradient: "linear-gradient(135deg, rgba(245, 158, 11, 0.15), rgba(217, 119, 6, 0.05))",
    benefits: ["'El rey de las frutas': rico en vitamina A y C", "Enzimas amilasas digestivas", "Protege la vista"],
    nutritions: { calories: 60, fat: 0.38, sugar: 13.7, carbohydrates: 15.0, protein: 0.82 }
  },
  {
    name: "Melon",
    spanishName: "Melón",
    id: 41,
    family: "Cucurbitaceae",
    order: "Cucurbitales",
    genus: "Cucumis",
    emoji: "🍈",
    accentColor: "#fb923c",
    bgGradient: "linear-gradient(135deg, rgba(251, 146, 60, 0.15), rgba(249, 115, 22, 0.05))",
    benefits: ["90% agua: hidratación pura", "Efecto diurético natural", "Bajo en calorías"],
    nutritions: { calories: 34, fat: 0.0, sugar: 8.0, carbohydrates: 8.0, protein: 0.0 }
  },
  {
    name: "Orange",
    spanishName: "Naranja",
    id: 2,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    emoji: "🍊",
    accentColor: "#f97316",
    bgGradient: "linear-gradient(135deg, rgba(249, 115, 22, 0.15), rgba(234, 88, 12, 0.05))",
    benefits: ["Cítrico emblemático para la inmunidad", "Aporte de hesperidina", "Favorece la piel sana"],
    nutritions: { calories: 43, fat: 0.2, sugar: 8.2, carbohydrates: 8.3, protein: 1.0 }
  },
  {
    name: "Papaya",
    spanishName: "Papaya / Lechoza",
    id: 42,
    family: "Caricaceae",
    order: "Caricales",
    genus: "Carica",
    emoji: "🥭",
    accentColor: "#fbbf24",
    bgGradient: "linear-gradient(135deg, rgba(251, 191, 36, 0.15), rgba(245, 158, 11, 0.05))",
    benefits: ["Enzima papaína (desinflama y digiere)", "Suaviza la mucosa estomacal", "Vitamina C y carotenoides"],
    nutritions: { calories: 43, fat: 0.4, sugar: 1.0, carbohydrates: 11.0, protein: 0.0 }
  },
  {
    name: "Passionfruit",
    spanishName: "Maracuyá / Fruta de la pasión",
    id: 70,
    family: "Passifloraceae",
    order: "Malpighiales",
    genus: "Passiflora",
    emoji: "🟡",
    accentColor: "#eab308",
    bgGradient: "linear-gradient(135deg, rgba(234, 179, 8, 0.15), rgba(202, 138, 4, 0.05))",
    benefits: ["Efecto relajante natural (pasiflorina)", "Altísima en fibra dietética", "Aroma tropical inigualable"],
    nutritions: { calories: 97, fat: 0.7, sugar: 11.2, carbohydrates: 23.4, protein: 2.2 }
  },
  {
    name: "Peach",
    spanishName: "Melocotón / Durazno",
    id: 87,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    emoji: "🍑",
    accentColor: "#fb923c",
    bgGradient: "linear-gradient(135deg, rgba(251, 146, 60, 0.15), rgba(249, 115, 22, 0.05))",
    benefits: ["Textura aterciopelada y jugosa", "Nutre la dermis", "Fácil asimilación digestiva"],
    nutritions: { calories: 39, fat: 0.25, sugar: 8.4, carbohydrates: 9.5, protein: 0.9 }
  },
  {
    name: "Pear",
    spanishName: "Pera",
    id: 4,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Pyrus",
    emoji: "🍐",
    accentColor: "#a3e635",
    bgGradient: "linear-gradient(135deg, rgba(163, 230, 53, 0.15), rgba(132, 204, 22, 0.05))",
    benefits: ["Hipoalergénica y suave para el estómago", "Rica en fibra insoluble", "Regula el colesterol"],
    nutritions: { calories: 57, fat: 0.1, sugar: 10.0, carbohydrates: 15.0, protein: 0.4 }
  },
  {
    name: "Persimmon",
    spanishName: "Caqui / Pérsimo",
    id: 52,
    family: "Ebenaceae",
    order: "Ericales",
    genus: "Diospyros",
    emoji: "🍅",
    accentColor: "#ea580c",
    bgGradient: "linear-gradient(135deg, rgba(234, 88, 12, 0.15), rgba(194, 65, 12, 0.05))",
    benefits: ["Sabor dulce meloso", "Rico en manganeso y vitamina A", "Poder antioxidante otoñal"],
    nutritions: { calories: 81, fat: 0.0, sugar: 18.0, carbohydrates: 18.0, protein: 0.0 }
  },
  {
    name: "Pineapple",
    spanishName: "Piña / Ananá",
    id: 10,
    family: "Bromeliaceae",
    order: "Poales",
    genus: "Ananas",
    emoji: "🍍",
    accentColor: "#eab308",
    bgGradient: "linear-gradient(135deg, rgba(234, 179, 8, 0.15), rgba(202, 138, 4, 0.05))",
    benefits: ["Enzima bromelina (antiinflamatoria potente)", "Diurética y desintoxicante", "Facilita digestiones pesadas"],
    nutritions: { calories: 50, fat: 0.12, sugar: 9.85, carbohydrates: 13.12, protein: 0.54 }
  },
  {
    name: "Pitahaya",
    spanishName: "Pitahaya Roja",
    id: 78,
    family: "Cactaceae",
    order: "Caryophyllales",
    genus: "Selenicereus",
    emoji: "🌺",
    accentColor: "#db2777",
    bgGradient: "linear-gradient(135deg, rgba(219, 39, 119, 0.15), rgba(190, 24, 93, 0.05))",
    benefits: ["Gran contenido de semillas con omega 3 y 6", "Favorece la regularidad intestinal", "Super hidratante"],
    nutritions: { calories: 36, fat: 0.4, sugar: 3.0, carbohydrates: 7.0, protein: 1.0 }
  },
  {
    name: "Plum",
    spanishName: "Ciruela",
    id: 71,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Prunus",
    emoji: "🟣",
    accentColor: "#9333ea",
    bgGradient: "linear-gradient(135deg, rgba(147, 51, 234, 0.15), rgba(126, 34, 206, 0.05))",
    benefits: ["Clásica aliada del tránsito intestinal", "Ácido clorogénico saciante", "Vitaminas K y C"],
    nutritions: { calories: 46, fat: 0.28, sugar: 9.92, carbohydrates: 11.42, protein: 0.7 }
  },
  {
    name: "Pomegranate",
    spanishName: "Granada",
    id: 79,
    family: "Lythraceae",
    order: "Myrtales",
    genus: "Punica",
    emoji: "🏮",
    accentColor: "#be123c",
    bgGradient: "linear-gradient(135deg, rgba(190, 18, 60, 0.15), rgba(159, 18, 57, 0.05))",
    benefits: ["Punicalaginas de altísimo poder anti-edad", "Protección de las arterias", "Regula la presión"],
    nutritions: { calories: 83, fat: 1.2, sugar: 13.7, carbohydrates: 18.7, protein: 1.7 }
  },
  {
    name: "Raspberry",
    spanishName: "Frambuesa",
    id: 23,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Rubus",
    emoji: "🫐",
    accentColor: "#e11d48",
    bgGradient: "linear-gradient(135deg, rgba(225, 29, 72, 0.15), rgba(190, 18, 60, 0.05))",
    benefits: ["Una de las frutas con mayor fibra por gramo", "Cetona de frambuesa aromática", "Muy baja en azúcar"],
    nutritions: { calories: 53, fat: 0.7, sugar: 4.4, carbohydrates: 12.0, protein: 1.2 }
  },
  {
    name: "Strawberry",
    spanishName: "Fresa / Frutilla",
    id: 3,
    family: "Rosaceae",
    order: "Rosales",
    genus: "Fragaria",
    emoji: "🍓",
    accentColor: "#ef4444",
    bgGradient: "linear-gradient(135deg, rgba(239, 68, 68, 0.15), rgba(220, 38, 38, 0.05))",
    benefits: ["Baja densidad calórica (ideal para control de peso)", "Ácido elágico antioxidante", "Vitamina C y manganeso"],
    nutritions: { calories: 32, fat: 0.3, sugar: 4.9, carbohydrates: 7.7, protein: 0.67 }
  },
  {
    name: "Tangerine",
    spanishName: "Mandarina",
    id: 77,
    family: "Rutaceae",
    order: "Sapindales",
    genus: "Citrus",
    emoji: "🍊",
    accentColor: "#f97316",
    bgGradient: "linear-gradient(135deg, rgba(249, 115, 22, 0.15), rgba(234, 88, 12, 0.05))",
    benefits: ["Fácil de pelar y consumir", "Aporte de folatos y betacriptoxantina", "Refuerza defensas"],
    nutritions: { calories: 45, fat: 0.4, sugar: 9.1, carbohydrates: 8.3, protein: 0.0 }
  },
  {
    name: "Tomato",
    spanishName: "Tomate",
    id: 5,
    family: "Solanaceae",
    order: "Solanales",
    genus: "Solanum",
    emoji: "🍅",
    accentColor: "#ef4444",
    bgGradient: "linear-gradient(135deg, rgba(239, 68, 68, 0.15), rgba(220, 38, 38, 0.05))",
    benefits: ["(Botánicamente fruta) Rey del licopeno protector de la próstata", "Ultra bajo en calorías", "Hidratante"],
    nutritions: { calories: 74, fat: 0.2, sugar: 2.6, carbohydrates: 3.9, protein: 0.9 }
  },
  {
    name: "Watermelon",
    spanishName: "Sandía / Patilla",
    id: 25,
    family: "Cucurbitaceae",
    order: "Cucurbitales",
    genus: "Citrullus",
    emoji: "🍉",
    accentColor: "#ef4444",
    bgGradient: "linear-gradient(135deg, rgba(239, 68, 68, 0.15), rgba(34, 197, 94, 0.05))",
    benefits: ["92% agua y citrulina (mejora oxigenación muscular)", "Excelente post-entreno refrescante", "Rica en licopeno"],
    nutritions: { calories: 30, fat: 0.2, sugar: 6.0, carbohydrates: 8.0, protein: 0.6 }
  }
];

export const SPANISH_TO_ENGLISH_MAP = {
  "manzana": "Apple",
  "albaricoque": "Apricot",
  "damasco": "Apricot",
  "aguacate": "Avocado",
  "palta": "Avocado",
  "platano": "Banana",
  "plátano": "Banana",
  "banano": "Banana",
  "mora": "Blackberry",
  "zarzamora": "Blackberry",
  "arandano": "Blueberry",
  "arándano": "Blueberry",
  "arandano azul": "Blueberry",
  "cereza": "Cherry",
  "pitahaya": "Dragonfruit",
  "fruta del dragon": "Dragonfruit",
  "durián": "Durian",
  "durian": "Durian",
  "feijoa": "Feijoa",
  "higo": "Fig",
  "uva": "Grape",
  "uvas": "Grape",
  "manzana verde": "GreenApple",
  "guayaba": "Guava",
  "kiwi": "Kiwi",
  "limon": "Lemon",
  "limón": "Lemon",
  "lima": "Lime",
  "lichi": "Lychee",
  "mango": "Mango",
  "melon": "Melon",
  "melón": "Melon",
  "naranja": "Orange",
  "papaya": "Papaya",
  "maracuya": "Passionfruit",
  "maracuyá": "Passionfruit",
  "melocoton": "Peach",
  "melocotón": "Peach",
  "durazno": "Peach",
  "pera": "Pear",
  "caqui": "Persimmon",
  "piña": "Pineapple",
  "pina": "Pineapple",
  "anana": "Pineapple",
  "ananá": "Pineapple",
  "ciruela": "Plum",
  "granada": "Pomegranate",
  "frambuesa": "Raspberry",
  "fresa": "Strawberry",
  "frutilla": "Strawberry",
  "mandarina": "Tangerine",
  "tomate": "Tomato",
  "sandia": "Watermelon",
  "sandía": "Watermelon",
  "patilla": "Watermelon"
};
